import type { Metadata } from "next";
import type { ReactNode } from "react";
import { StaticPageShell } from "@/components/landing/StaticPageShell";
import { PageHero } from "@/components/landing/PageHero";
import { LegalDocument, type LegalSection } from "@/components/landing/LegalDocument";

export const metadata: Metadata = {
  title: "Terms of Service | Ficungini",
  description: "The terms that govern your use of Ficungini.",
};

type Item = string | { h: string } | { list: string[] };

// Text wrapped in ** is rendered bold.
const rich = (text: string): ReactNode =>
  text.split("**").map((part, i) => (i % 2 ? <strong key={i}>{part}</strong> : part));

const body = (...items: Item[]): ReactNode => (
  <>
    {items.map((item, i) => {
      if (typeof item === "string") return <p key={i}>{rich(item)}</p>;
      if ("h" in item)
        return (
          <h3 key={i} className="pt-2 text-base font-bold text-ink-900 font-sans-title">
            {item.h}
          </h3>
        );
      return (
        <ul key={i}>
          {item.list.map((li) => (
            <li key={li}>{li}</li>
          ))}
        </ul>
      );
    })}
  </>
);

const sections: LegalSection[] = [
  {
    id: "introduction",
    title: "Introduction",
    body: body(
      `These Terms of Service ("Terms") govern access to and use of the Ficungini platform, websites, applications, APIs, discovery services, workspaces, and related services (collectively, the "Services").`,
      `The Services are provided by **RITH** ("RITH", "we", "us", or "our"), and Ficungini is the product and platform operated by RITH.`,
      `By creating an account, accessing the Services, or using the Services, you agree to these Terms. If you are using Ficungini on behalf of an organization, you represent that you have authority to bind that organization to these Terms.`,
    ),
  },
  {
    id: "definitions",
    title: "Definitions",
    body: body(
      "For these Terms:",
      `**"Customer"** means the individual or organization subscribing to or using the Services.`,
      `**"User"** means an individual authorized by a Customer to access the Services.`,
      `**"Customer Content"** means documents, tender information, evidence, data, instructions, files, and other information submitted to Ficungini by or on behalf of a Customer.`,
      `**"Profile Information"** means business information voluntarily provided by a Customer for Ficungini's Profile-Specific Discovery Engine, including eligibility criteria, technical capabilities, financial capabilities, qualifications, strengths, weaknesses, experience, geographic capabilities, and other relevant business information.`,
      `**"Ficungini"** means the software platform, products, and services operated by RITH.`,
      `**"Output"** means analysis, findings, discovery results, reports, matches, summaries, or other results generated by the Services from Customer Content, Profile Information, or User instructions.`,
    ),
  },
  {
    id: "acceptance",
    title: "Acceptance of Terms",
    body: body(
      "By accessing or using Ficungini, you agree to these Terms.",
      "If you do not agree to these Terms, you may not access or use the Services.",
      "If you are using Ficungini on behalf of a company, government organization, partnership, or other legal entity, you represent that you are authorized to accept these Terms on its behalf.",
    ),
  },
  {
    id: "eligibility",
    title: "Eligibility",
    body: body(
      "You must have legal capacity to enter into a binding agreement to use the Services.",
      "Ficungini is primarily intended for business, professional, institutional, and enterprise use.",
      "You may not use the Services where doing so would violate applicable law or regulations.",
    ),
  },
  {
    id: "account-registration",
    title: "Account Registration",
    body: body(
      "Certain Services require an account.",
      "You agree to provide accurate information when creating and maintaining your account. You are responsible for:",
      {
        list: [
          "Maintaining the confidentiality of your credentials",
          "Maintaining access to your registered email account",
          "Maintaining control of your TOTP authentication mechanism",
          "All activity conducted through your account",
          "Promptly notifying RITH of suspected unauthorized access",
        ],
      },
      "RITH may suspend or restrict an account where reasonably necessary to protect the Services, users, Customer Content, or other parties.",
    ),
  },
  {
    id: "totp",
    title: "TOTP Authentication",
    body: body(
      "Ficungini requires Time-based One-Time Password (TOTP) authentication for platform access.",
      "Users must successfully complete the required TOTP authentication to access the platform.",
      "Users are responsible for protecting their TOTP authentication device, recovery mechanisms, and account credentials.",
      "If you lose control of your TOTP authentication mechanism or believe your account has been compromised, you must notify RITH promptly.",
    ),
  },
  {
    id: "customer-workspaces",
    title: "Customer Workspaces",
    body: body(
      "Ficungini may provide customers with encrypted workspaces for storing and processing tender information.",
      "Customers are responsible for determining what information they upload and for ensuring that they have the necessary rights, permissions, licenses, and lawful basis to provide that information to RITH.",
      "Customers must not intentionally upload information that they are prohibited from sharing or processing.",
      "RITH may process Customer Content as necessary to provide the Services requested by the Customer.",
    ),
  },
  {
    id: "content-ownership",
    title: "Customer Content Ownership",
    body: body(
      "As between RITH and the Customer, the Customer retains its rights in Customer Content.",
      "The Customer grants RITH a limited, non-exclusive right to host, transmit, reproduce, process, analyze, and otherwise use Customer Content solely as reasonably necessary to:",
      {
        list: [
          "Provide the Services",
          "Perform Customer-authorized processing",
          "Maintain and secure the Services",
          "Prevent abuse and security incidents",
          "Provide customer support",
          "Comply with applicable law",
          "Enforce these Terms",
        ],
      },
      "RITH does not acquire ownership of Customer Content merely because the Customer uploads it to Ficungini.",
    ),
  },
  {
    id: "customer-responsibilities",
    title: "Customer Responsibilities",
    body: body(
      "The Customer is responsible for:",
      {
        list: [
          "The accuracy of information supplied to Ficungini",
          "The legality of uploaded content",
          "Obtaining necessary rights and permissions",
          "Reviewing generated Outputs",
          "Maintaining appropriate internal approval processes",
          "Ensuring that Users comply with these Terms",
          "Protecting account credentials and authentication factors",
          "Configuring connected third-party systems appropriately",
        ],
      },
      "The Customer must not use Ficungini to violate applicable law, contractual obligations, intellectual-property rights, confidentiality obligations, or privacy rights.",
    ),
  },
  {
    id: "profile-specific-discovery",
    title: "Profile-Specific Discovery",
    body: body(
      "Ficungini provides a Profile-Specific Discovery Engine rather than relying solely on generic discovery.",
      "A Customer may voluntarily provide Profile Information, including eligibility criteria, technical capabilities, financial capabilities, qualifications, strengths, weaknesses, experience, and other business characteristics.",
      "Profile-Specific Discovery requires the Customer's authorization.",
      "When authorized, RITH may retain and process Profile Information for the purpose of identifying and presenting procurement opportunities and discovery results relevant to that Customer's stated business profile.",
      "The quality and completeness of Profile Information may affect the relevance of discovery results. Customers are responsible for keeping their Profile Information reasonably accurate and current.",
      { h: "Withdrawal" },
      "A Customer may withdraw authorization for Profile-Specific Discovery.",
      "If authorization is withdrawn, RITH will stop using the applicable Profile Information for the Profile-Specific Discovery purpose, subject to applicable legal, security, contractual, and technical requirements.",
      "Disabling the authorization disables access to Profile-Specific Discovery because that functionality depends on the authorized customer profile.",
      "Withdrawal does not affect processing that was lawfully performed before withdrawal.",
    ),
  },
  {
    id: "no-guarantee",
    title: "No Guarantee of Opportunity Suitability",
    body: body(
      "Discovery results are intended to assist customers in identifying potentially relevant procurement opportunities.",
      "RITH does not guarantee that:",
      {
        list: [
          "A discovered tender is suitable for the Customer",
          "The Customer is legally or technically eligible",
          "The Customer satisfies every tender requirement",
          "A tender will remain open",
          "A tender will be awarded to the Customer",
          "A Customer will win a tender",
          "A discovery result is complete",
          "Every relevant opportunity will be identified",
        ],
      },
      "Customers remain responsible for independently verifying tender requirements, deadlines, eligibility, commercial conditions, and other relevant information before taking action.",
    ),
  },
  {
    id: "automated-processing",
    title: "Automated Processing and Outputs",
    body: body(
      "Ficungini uses automated computational systems and, where applicable, machine-learning or model-based systems to provide certain Services.",
      "Outputs may include:",
      {
        list: [
          "Requirement analysis",
          "Compliance findings",
          "Evidence matching",
          "Tender analysis",
          "Discovery results",
          "Reports",
          "Summaries",
          "Other generated information",
        ],
      },
      "Automated Outputs are generated from the information available to the relevant Service.",
      "Customers must independently review Outputs before relying on them for legal, financial, commercial, regulatory, procurement, or other material decisions.",
      "RITH does not represent that every Output will be complete, accurate, current, or error-free.",
    ),
  },
  {
    id: "no-professional-advice",
    title: "No Professional Advice",
    body: body(
      "Ficungini does not provide legal, financial, tax, accounting, regulatory, or other professional advice merely by generating an Output.",
      "Customers should obtain appropriate professional advice where required.",
    ),
  },
  {
    id: "model-training",
    title: "Paid Customer Data and Model Training",
    body: body(
      "RITH does not use data belonging to paid customers to train, fine-tune, or improve general-purpose artificial intelligence or machine-learning models.",
      "Paid Customer Content and Profile Information are not incorporated into general-purpose model-training datasets.",
      "This does not prevent RITH from processing customer information through computational or model-based systems when such processing is necessary to provide the Services requested or authorized by the Customer.",
    ),
  },
  {
    id: "third-party-services",
    title: "Third-Party Services and Integrations",
    body: body(
      "Ficungini may integrate with or depend on third-party services, including ERP systems, infrastructure providers, authentication services, email providers, payment providers, cloud infrastructure, and computational or model providers.",
      "Use of a third-party service may be subject to that provider's own terms and policies.",
      "The Customer is responsible for ensuring that its use of connected third-party systems is authorized and appropriately configured.",
      "RITH is not responsible for failures or security incidents caused solely by third-party systems outside RITH's reasonable control.",
    ),
  },
  {
    id: "api-erp",
    title: "API and ERP Integrations",
    body: body(
      "Where Ficungini supports API or ERP integrations, data transmitted through such integrations is transmitted through encrypted communication channels.",
      "Customers are responsible for maintaining appropriate credentials, permissions, and security controls for their connected systems.",
      "Customers authorize RITH to exchange the information reasonably necessary to perform the integration that the Customer has configured.",
    ),
  },
  {
    id: "tender-lifecycle",
    title: "Tender Workspace Lifecycle",
    body: body(
      "After a tender reaches its designated closing state, applicable workspace documents may be packaged into a ZIP archive for customer delivery.",
      "The Customer's authorized administrator may specify the destination email address for delivery. The destination email address does not need to be a fixed RITH or Ficungini email address.",
      "After the applicable export and delivery process has been completed, the corresponding tender workspace documents are deleted from RITH's active server environment in accordance with the applicable data lifecycle.",
      "Backup or disaster-recovery systems may retain copies for a limited period according to their applicable lifecycle.",
    ),
  },
  {
    id: "intellectual-property",
    title: "Intellectual Property",
    body: body(
      "The Services, including the Ficungini software, platform architecture, user interface, software code, databases, designs, trademarks, documentation, workflows, and other materials provided by RITH, are owned by or licensed to RITH and are protected by applicable intellectual-property laws.",
      "Except for the limited rights expressly granted under these Terms, no intellectual-property rights are transferred to the Customer.",
      "The Customer may not:",
      {
        list: [
          "Copy the Services",
          "Reverse engineer the Services except where legally permitted",
          "Decompile or disassemble the software except where legally permitted",
          "Attempt to obtain source code",
          "Circumvent security controls",
          "Create unauthorized derivative works",
          "Resell or sublicense the Services without authorization",
          "Use the Services to build a substantially similar competing product through unauthorized means",
        ],
      },
    ),
  },
  {
    id: "feedback",
    title: "Feedback",
    body: body(
      "If a Customer voluntarily provides suggestions, ideas, recommendations, or other feedback regarding Ficungini, RITH may use that feedback without restriction or obligation to compensate the Customer, provided that RITH does not thereby obtain ownership of the Customer's confidential information.",
    ),
  },
  {
    id: "acceptable-use",
    title: "Acceptable Use",
    body: body(
      "You may not use Ficungini to:",
      {
        list: [
          "Violate applicable law",
          "Infringe intellectual-property rights",
          "Obtain unauthorized access to systems or data",
          "Circumvent authentication or security controls",
          "Upload malicious software",
          "Conduct unauthorized security testing",
          "Interfere with platform availability",
          "Attempt to access another customer's workspace",
          "Scrape or extract platform data through unauthorized means",
          "Abuse API limits or platform infrastructure",
          "Misrepresent your identity or authority",
          "Use the Services for fraudulent purposes",
          "Use the Services to facilitate unlawful activity",
        ],
      },
      "RITH may suspend or terminate access where it reasonably determines that these restrictions have been violated.",
    ),
  },
  {
    id: "confidentiality",
    title: "Confidentiality",
    body: body(
      "Each party may receive confidential information belonging to the other party.",
      "The receiving party will use reasonable measures to protect confidential information and will not disclose it except:",
      {
        list: [
          "To personnel and service providers who need it to perform the applicable obligations",
          "With the disclosing party's authorization",
          "Where required by law",
          "Where necessary to protect legal rights or security",
        ],
      },
      "Confidential information does not include information that is publicly available through no breach of obligation, was already lawfully known, is independently developed without use of confidential information, or is lawfully received from a third party without confidentiality restrictions.",
      "Additional confidentiality obligations may be established through an applicable enterprise agreement or NDA.",
    ),
  },
  {
    id: "privacy",
    title: "Privacy",
    body: (
      <>
        <p>
          RITH&apos;s collection and processing of personal information is described in the{" "}
          <a href="/privacy" className="font-medium text-pantone hover:text-pantone-700">
            Ficungini Privacy Policy
          </a>
          .
        </p>
        <p>The Privacy Policy forms part of these Terms by reference.</p>
        <p>
          Where an enterprise customer has entered into a Data Processing Agreement with RITH, the applicable DPA governs
          the processing of personal data covered by that agreement.
        </p>
      </>
    ),
  },
  {
    id: "fees",
    title: "Fees and Subscriptions",
    body: body(
      "Certain Ficungini Services require payment of subscription or usage fees.",
      "Applicable fees, billing periods, taxes, usage limits, and payment terms will be presented during purchase or established in the applicable order form or customer agreement.",
      "Unless otherwise specified, fees are non-refundable except where required by applicable law or expressly agreed in writing.",
      "RITH may change pricing for future subscription periods by providing reasonable notice.",
    ),
  },
  {
    id: "suspension",
    title: "Suspension",
    body: body(
      "RITH may temporarily suspend access to the Services where reasonably necessary to:",
      {
        list: [
          "Protect security",
          "Prevent unauthorized access",
          "Address abuse",
          "Respond to a security incident",
          "Comply with law",
          "Prevent damage to the Services or other customers",
          "Address non-payment",
        ],
      },
      "Where reasonably practicable, RITH will provide notice before suspension.",
    ),
  },
  {
    id: "termination",
    title: "Termination",
    body: body(
      "A Customer may terminate its use of the Services according to the applicable subscription or customer agreement.",
      "RITH may terminate or suspend access where the Customer materially breaches these Terms, fails to pay applicable fees, uses the Services unlawfully, or creates a material security or operational risk.",
      "Upon termination, access to the Services may cease and applicable Customer Content will be handled according to the applicable data-retention and deletion procedures.",
    ),
  },
  {
    id: "availability",
    title: "Availability",
    body: body(
      "RITH will make commercially reasonable efforts to maintain the availability and reliability of the Services.",
      "The Services may occasionally be unavailable due to:",
      {
        list: [
          "Scheduled maintenance",
          "Emergency maintenance",
          "Infrastructure failures",
          "Third-party failures",
          "Network failures",
          "Security incidents",
          "Events outside RITH's reasonable control",
        ],
      },
      "Specific availability commitments may be established through an applicable enterprise SLA.",
    ),
  },
  {
    id: "security",
    title: "Security",
    body: body(
      "RITH maintains technical and organizational safeguards designed to protect the Services and Customer Content. These include, as applicable:",
      {
        list: [
          "Encrypted customer workspaces",
          "Encrypted data transmission",
          "Encrypted API and ERP communications",
          "Mandatory TOTP authentication",
          "Access controls",
          "Workspace isolation",
          "Security logging",
          "Monitoring",
          "Controlled data retention and deletion",
          "Backup and recovery mechanisms",
          "Incident-response procedures",
        ],
      },
      "No internet-connected service can guarantee absolute security.",
    ),
  },
  {
    id: "disclaimers",
    title: "Disclaimers",
    body: body(
      `To the maximum extent permitted by applicable law, the Services are provided on an "as available" basis.`,
      "RITH does not warrant that:",
      {
        list: [
          "The Services will always be uninterrupted",
          "Every Output will be accurate",
          "Every tender or opportunity will be discovered",
          "Every discovered opportunity will be suitable",
          "Customer Content will always produce the expected result",
          "The Services will satisfy every particular business requirement",
          "The Services will produce a particular commercial outcome",
        ],
      },
      "Nothing in these Terms excludes warranties or rights that cannot legally be excluded.",
    ),
  },
  {
    id: "limitation-of-liability",
    title: "Limitation of Liability",
    body: body(
      "To the maximum extent permitted by applicable law, RITH will not be liable for indirect, incidental, special, consequential, exemplary, or punitive damages, or for loss of profits, revenue, business opportunity, goodwill, or anticipated savings arising from use of the Services.",
      "RITH's aggregate liability arising from the Services will, to the maximum extent permitted by applicable law, be limited to the amount actually paid by the Customer to RITH for the Services during the 12 months preceding the event giving rise to the claim.",
      "This limitation does not apply to liability that cannot legally be limited or excluded under applicable law.",
      "For enterprise customers, liability may instead be governed by the applicable negotiated agreement.",
    ),
  },
  {
    id: "indemnification",
    title: "Indemnification",
    body: body(
      "To the extent permitted by applicable law, the Customer agrees to defend, indemnify, and hold harmless RITH and its officers, employees, and representatives from claims, losses, liabilities, and expenses arising from:",
      {
        list: [
          "The Customer's unlawful use of the Services",
          "The Customer's violation of these Terms",
          "Customer Content that infringes third-party rights",
          "The Customer's failure to obtain necessary rights or permissions for Customer Content",
          "Unauthorized use of the Customer's account caused by the Customer's failure to protect credentials or authentication mechanisms",
        ],
      },
      "Enterprise customers may have different indemnification obligations under negotiated agreements.",
    ),
  },
  {
    id: "changes-to-services",
    title: "Changes to the Services",
    body: body(
      "RITH may modify, improve, replace, or discontinue features of Ficungini from time to time.",
      "We will make reasonable efforts to avoid materially reducing the core functionality of a paid Service during an active subscription period, except where changes are required for security, legal, regulatory, technical, or operational reasons.",
    ),
  },
  {
    id: "changes-to-terms",
    title: "Changes to These Terms",
    body: body(
      "RITH may update these Terms periodically.",
      "If changes materially affect the Customer's rights or obligations, RITH may provide notice through the Services, email, or another appropriate mechanism.",
      "Continued use of the Services after the effective date of updated Terms constitutes acceptance of the updated Terms to the extent permitted by law.",
    ),
  },
  {
    id: "governing-law",
    title: "Governing Law",
    body: body(
      "These Terms are governed by the laws of **India**, unless a separate written agreement with the Customer specifies otherwise.",
      "Subject to any mandatory rights under applicable law, disputes will be subject to the jurisdiction specified in the applicable customer agreement.",
      "If no separate jurisdiction is specified, the courts of a jurisdiction in India to be specified will have jurisdiction over disputes arising from these Terms.",
    ),
  },
  {
    id: "force-majeure",
    title: "Force Majeure",
    body: body(
      "RITH will not be responsible for failure or delay caused by circumstances beyond its reasonable control, including:",
      {
        list: [
          "Natural disasters",
          "War",
          "Terrorism",
          "Government actions",
          "Internet or telecommunications failures",
          "Major infrastructure failures",
          "Cybersecurity events affecting third-party infrastructure",
          "Power failures",
          "Labor disruptions",
          "Other events beyond reasonable control",
        ],
      },
    ),
  },
  {
    id: "notices",
    title: "Notices",
    body: (
      <>
        <p>Legal notices to RITH must be sent to:</p>
        <p>
          <strong>RITH</strong>
          <br />
          Registered address to be added
          <br />
          India
        </p>
        <p>
          <strong>Legal Contact:</strong>{" "}
          <a href="mailto:legal@ficungini.ai" className="font-medium text-pantone hover:text-pantone-700">
            legal@ficungini.ai
          </a>
        </p>
        <p>
          Notices to Customers may be delivered through the registered email address, Ficungini account, or other contact
          information associated with the Customer.
        </p>
      </>
    ),
  },
  {
    id: "assignment",
    title: "Assignment",
    body: body(
      "The Customer may not assign or transfer these Terms without RITH's prior written consent, except where permitted as part of a merger, acquisition, or corporate restructuring.",
      "RITH may assign these Terms in connection with a merger, acquisition, restructuring, financing, or transfer of substantially all relevant assets.",
    ),
  },
  {
    id: "severability",
    title: "Severability",
    body: body(
      "If any provision of these Terms is determined to be invalid or unenforceable, the remaining provisions will remain in effect to the extent permitted by law.",
    ),
  },
  {
    id: "entire-agreement",
    title: "Entire Agreement",
    body: body(
      "These Terms, together with the applicable Privacy Policy, order forms, Data Processing Agreement, SLA, and other written agreements applicable to the Customer, constitute the agreement governing use of the Services.",
      "Where a negotiated enterprise agreement conflicts with these Terms, the negotiated agreement controls to the extent expressly stated.",
    ),
  },
  {
    id: "contact",
    title: "Contact",
    body: (
      <>
        <p>For questions concerning these Terms:</p>
        <p>
          <strong>RITH</strong>
          <br />
          Ficungini
          <br />
          Registered address to be added
          <br />
          India
        </p>
        <p>
          <strong>Legal:</strong>{" "}
          <a href="mailto:legal@ficungini.ai" className="font-medium text-pantone hover:text-pantone-700">
            legal@ficungini.ai
          </a>
          <br />
          <strong>Privacy:</strong>{" "}
          <a href="mailto:privacy@ficungini.ai" className="font-medium text-pantone hover:text-pantone-700">
            privacy@ficungini.ai
          </a>
        </p>
      </>
    ),
  },
];

export default function TermsPage() {
  return (
    <StaticPageShell>
      <PageHero
        kicker="LEGAL"
        title="Terms of Service"
        description="The terms that govern your use of Ficungini."
      />
      <div aria-hidden className="mx-auto h-px max-w-6xl bg-ink-200" />
      <LegalDocument
        effectiveDate="29 September 2026"
        readTime="~15 min read"
        organization={{
          name: "RITH (operating Ficungini)",
          lines: ["Registered address to be added", "India"],
          email: "legal@ficungini.ai",
        }}
        sections={sections}
      />
    </StaticPageShell>
  );
}
